### ISSUE TITLE
No some SNMPv3 configuration fields on inventory page

### ISSUE THREAD

**Issue by turkovda** [QualiSystems/Cisco-NXOS-Switch-Shell-2G#15]
### Issue details

SNMPv3 Authentication Protocol and Privacy Protocol don't exist on configuration inventory page:
![image](https://user-images.githubusercontent.com/59359491/93988645-a5162a80-fd91-11ea-9a2d-56cfb8ab0ddd.png)

### Steps to reproduce

1. Add new Inventory based on Cisco NXOS Shell
2. Observe configuration fields

### Actual Result
No SNMPv3 Authentication Protocol and Privacy Protocol

**Comment by Costya-Y** [comment]
Fixed
